server: 
  port: 8761 #指定服务端口
eureka: 
  client:
    registerWithEureka: false #不作为一个客户端注册到注册中心
    fetchRegistry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #通过eureka.client.registerWithEureka:false和fetchRegistry:false来表明自己是一个eureka server.